export const VOLUMIO_ALBUM_LIST = 'VOLUMIO_ALBUM_LIST';
export const VOLUMIO_CONNECT = 'VOLUMIO_CONNECT';
export const VOLUMIO_DISCONNECT = 'VOLUMIO_DISCONNECT';
export const VOLUMIO_STATE_UPDATE = 'VOLUMIO_STATE_UPDATE';
export const VOLUMIO_QUEUE_UPDATE = 'VOLUMIO_QUEUE_UPDATE';
export const FAVORITES_LOADED = 'FAVORITES_LOADED';
export const CURRENT_VIEW = 'CURRENT_VIEW';
export const TOGGLE_TIMR_COUNTDOWN = 'TOGGLE_TIMR_COUNTDOWN';
